version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pkki-itera:latest
    container_name: pkki-itera-app
    restart: unless-stopped
    ports:
      - "3003:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=pkki_itera
      - DB_USERNAME=pkki_user
      - DB_PASSWORD=secure_password
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - storage_data:/var/www/storage/app
      - logs_data:/var/www/storage/logs
    depends_on:
      - mysql
      - redis
    networks:
      - pkki-network

  mysql:
    image: mysql:8.0
    container_name: pkki-itera-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pkki_itera
      MYSQL_USER: pkki_user
      MYSQL_PASSWORD: secure_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - "3306:3306"
    networks:
      - pkki-network

  redis:
    image: redis:7-alpine
    container_name: pkki-itera-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - pkki-network

  nginx:
    image: nginx:alpine
    container_name: pkki-itera-nginx
    restart: unless-stopped
    ports:
      - "3003:80"
      - "3443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - storage_data:/var/www/storage/app
    depends_on:
      - app
    networks:
      - pkki-network

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    image: pkki-itera:latest
    container_name: pkki-itera-queue
    restart: unless-stopped
    command: php artisan queue:work --verbose --tries=3 --timeout=60
    environment:
      - APP_ENV=production
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=pkki_itera
      - DB_USERNAME=pkki_user
      - DB_PASSWORD=secure_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - storage_data:/var/www/storage/app
      - logs_data:/var/www/storage/logs
    depends_on:
      - mysql
      - redis
    networks:
      - pkki-network

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: pkki-itera:latest
    container_name: pkki-itera-scheduler
    restart: unless-stopped
    command: >
      sh -c "while true; do
        php artisan schedule:run --verbose --no-interaction &
        sleep 60
      done"
    environment:
      - APP_ENV=production
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=pkki_itera
      - DB_USERNAME=pkki_user
      - DB_PASSWORD=secure_password
    volumes:
      - storage_data:/var/www/storage/app
      - logs_data:/var/www/storage/logs
    depends_on:
      - mysql
      - redis
    networks:
      - pkki-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  storage_data:
    driver: local
  logs_data:
    driver: local

networks:
  pkki-network:
    driver: bridge
