name: Bug report
description: File a bug report to help us improve
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Please provide step-by-step instructions
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera

  - type: dropdown
    id: device
    attributes:
      label: What device are you using?
      options:
        - Desktop
        - Mobile
        - Tablet

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Please provide environment information
      placeholder: |
        - OS: [e.g. Windows 10, macOS Big Sur, Ubuntu 20.04]
        - PHP Version: [e.g. 8.2.0]
        - Laravel Version: [e.g. 11.9]
        - Browser Version: [e.g. Chrome 120]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I have tested this on the latest version
          required: false
